apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8deploy
  template:
    metadata:
      labels:
        app: k8deploy
    spec:
      containers:
      - name: k8deploy
        image: georgeulahannan/dockerplugin:${BUILD_NUMBER}
        ports:
        - containerPort: 80
