node {
  stage('List pods') {
    withKubeConfig([credentialsId: 'kube-ca',
                    caCertificate: 'kube-ca',
                    serverUrl: 'https://192.168.49.2:8443',
                    contextName: 'minikube',
                    clusterName: 'minikube',
                    namespace: 'default'
                    ]) {
      sh 'kubectl get pods'
    }
  }
}
